---

- name: Build AMI
  hosts: local
  connection: local
  gather_facts: False

  vars:
    version_string: "{{ hostvars[groups['ec2'][0]]['version_string']['stdout'] }}"
    snapshot_description: VyOS AMI (HVM) {{ version_string }}

    ami_name: VyOS (HVM) {{ version_string }}
    ami_description: The VyOS AMI is an EBS-backed, HVM image. It is an open-source Linux-based network operating system that provides software-based network routing, firewall, and VPN functionality.
    ami_architecture: x86_64
    ami_virtualization_type: hvm
    ami_root_device_name: /dev/xvda

  tasks:
    - name: Create a snapshot of the EBS volume
      ec2_snapshot:
        region: "{{ ec2_region }}"
        device_name: /dev/xvdf
        instance_id: "i-0f847273437a7f662"
        description: "null"
      register: ec2_snap
